### PR TITLE
Upgrade to hdk 0.4.0, hdi 0.5.0 and Holochain 0.4.0 release binaries

### PR DESCRIPTION
**Pull request by pjkundert**
Upgraded to feature/source branch of nix-overlay, to use Holochain 0.4.0 release binaries built by holochain/holochain.

Builds and tests successfully on macOS aarch64, and Linux x86_64 and aarch64.

### CODE REVIEW

**Comment by pjkundert** [comment]
The only strange thing is the last line in the Github Actions "Run Tests":

```
      ✔ should get large memory (5228ms)


  2 passing (25s)

/home/runner/work/_temp/5d40864a-1b66-4d1f-a6e7-67e5884d908c.sh: line 11: [: : integer expression expected
```

**Comment by pjkundert** [comment]
Also, we should merge the nix-overlay pull and then use that commit's hash (and SHA-256) in pkgs.nix, before merging this.  And, of course, reference the spartan-holochain-council/nix-overlay instead of pjkundert/nix-overlay in pkgs.nix...

**Comment by pjkundert** [comment]
Actually, I may have spoken too soon -- on my UTM x86_64 VM running Ubuntu 24.04, the `make test` fails, while it works fine on the arm64 VM running the same Linux.  I don't have a native x86_64 platform handy right now to test on.

image

**Comment by mjbrisebois** [comment]
> The only strange thing is the last line in the Github Actions "Run Tests":

There must be something wrong with [this line](https://github.com/spartan-holochain-counsel/zome-mere-memory/actions/runs/12471240168/workflow#L41) in the workflow

**Review by mjbrisebois — APPROVED** [review]
Passes for me on aarch64 darwin and x64 linux

**Pull request merged**
